### PR TITLE
Added link to python3 version

### PR DESCRIPTION
**Pull request by evelynmitchell**

### CODE REVIEW

**Comment by Cabalist** [comment]
This should not be merged.   The first line of the README at that link states that the project is deprecated and redirects you here:

>  Important Deprecation Note: This was a py3 compatibility port of https://github.com/linsomniac/python-memcached
which since then has added py23. So you should use that.

**Comment by Cabalist** [comment]
I am looking for a maintained version of this repo if anyone knows what the modern equivalent is...

**Comment by evelynmitchell** [comment]
https://github.com/pinterest/pymemcache looks to be active.

**Comment by linsomniac** [comment]
Thank you for the PR, but as mentioned by @Cabalist I'll pass on merging it.

**Pull request closed without merging**
