### PR TITLE
Add flake8 check to Travis

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by timgraham** [comment]
Other warnings from `hacking`:
```
./memcache.py:783:1: H404  multi line docstring should start without a leading new line
./memcache.py:783:1: H405  multi line docstring summary not separated with an empty line
./tests/test_memcache.py:7:28: H301  one import per line
./tests/test_memcache.py:37:11: H101  Use TODO(NAME)
```
I'm not sure they provide much value. If I were maintaining the package I'd remove `hacking` from test dependencies and not worry about those warnings. Other opinions?

**Comment by linsomniac** [comment]
Thanks for the PR, I think it's worth some clean up, I'll work on that.

**Comment by linsomniac** [comment]
@timgraham : I fixed up the things it was reporting, but it is failing on py33 with an error that looks entirely related to Travis/tox/flake8:

      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/hacking/checks/except_checks.py", line 71, in is_none
        return isinstance(node, ast.NameConstant) and node.value is None
    AttributeError: 'module' object has no attribute 'NameConstant'

Any ideas?

**Comment by timgraham** [comment]
Looks like `ast.NameConstant` is new in Python 3.4 so it's a bug in hacking if they claim to support Python 3.3. We could try to skip flake8 on Python 3.3 or just drop support for Python 3.3 entirely -- I don't think it's used much anymore.

**Pull request merged**
