### PR TITLE
python 2.7 Unicode compatible.

### PR DESCRIPTION
**Pull request by dzhuang**
Extracted from kmaglione's patch (#74) and solving #79.

### CODE REVIEW

**Comment by niconoe** [comment]
Any chance to have this merged and a new release pushed at PyPI? Or is it blocked by the maintainer change? Anything I can do to help?

**Comment by timgraham** [comment]
I'm not a maintainer, but the test from #79 should be added to the patch.

**Comment by niconoe** [comment]
I added it, it's now available in PR 10.

**Comment by dzhuang** [comment]
As this patch has been integrated into #107, I am now closing it.

**Pull request closed without merging**
